base = read.csv("tabela_com_todos_os_indicadores_selecionados_e_desvios.csv", sep = ",")
indicador = read.csv("INDICADOR_114.csv",sep = ",")
indicador[1,]

base = merge(base, indicador, by = c("COD_MUNICIPIO", "ANO"))
base$DESVIOS_MELHOR_INDICADOR_114 = 0

keeps <- c("COD_MUNICIPIO","ANO", "COD_UF.x", "NOME_UF.x", "COD_MESO.x", "NOME_MESO.x", "COD_MICRO.x", "NOME_MICRO.x","NOME_MUNICIPIO.x","INDICADOR_001","DESVIOS_MELHOR_INDICADOR_001",
           "INDICADOR_002","DESVIOS_MELHOR_INDICADOR_002"
           ,"INDICADOR_004","DESVIOS_MELHOR_INDICADOR_004"
           ,"INDICADOR_007","DESVIOS_MELHOR_INDICADOR_007"
           ,"INDICADOR_009","DESVIOS_MELHOR_INDICADOR_009"
           ,"INDICADOR_020","DESVIOS_MELHOR_INDICADOR_020"
           ,"INDICADOR_021","DESVIOS_MELHOR_INDICADOR_021"
           ,"INDICADOR_035","DESVIOS_MELHOR_INDICADOR_035"
           ,"INDICADOR_041","DESVIOS_MELHOR_INDICADOR_041"
           ,"INDICADOR_101","DESVIOS_MELHOR_INDICADOR_101"
           ,"INDICADOR_102","DESVIOS_MELHOR_INDICADOR_102"
           ,"INDICADOR_103","DESVIOS_MELHOR_INDICADOR_103"
           ,"INDICADOR_104","DESVIOS_MELHOR_INDICADOR_104"
           ,"INDICADOR_105","DESVIOS_MELHOR_INDICADOR_105"
           ,"INDICADOR_106","DESVIOS_MELHOR_INDICADOR_106"
           ,"INDICADOR_107","DESVIOS_MELHOR_INDICADOR_107"
           ,"INDICADOR_108","DESVIOS_MELHOR_INDICADOR_108"
           ,"INDICADOR_109","DESVIOS_MELHOR_INDICADOR_109"
           ,"INDICADOR_110","DESVIOS_MELHOR_INDICADOR_110"
           ,"INDICADOR_111","DESVIOS_MELHOR_INDICADOR_111"
           ,"INDICADOR_112","DESVIOS_MELHOR_INDICADOR_112"
           ,"INDICADOR_113","DESVIOS_MELHOR_INDICADOR_113"
           ,"INDICADOR_114","DESVIOS_MELHOR_INDICADOR_114")
base = base[,keeps,drop=FALSE]
nrow(base)
base[1,]
write.csv(base, "tabela_com_todos_os_indicadores_selecionados_e_desvios.csv", row.names = F)
